# This is a basic workflow to help you get started with Actions

name: github push test CI

on:
  repository_dispatch:
    types: [magic]
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * *
#  watch:
#    types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@main

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hello, world!"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          touch hello3
          echo "fuck you" >> hello1
          echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh   -T git@github.com
      - name: Commit files
        run: |
         git config --local user.email "baozhu.zuo@gmail.com"
         git config --local user.name "I'm Code Bot"
         git add --all
         git commit -m "Add changes" -a
      - name: Push changes
        uses: baorepo/magic@main
        with:
         github_token: ${{ secrets.SSH_PRIVATE_KEY }}
         branch: ${{ github.ref }}
