# This is a basic workflow to help you get started with Actions

name: github push test CI

on:
  repository_dispatch:
    types: [magic]
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * *
#  watch:
#    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        echo "hello word"
    - name: Commit files
      run: |
        git config --local user.email "baozhu.zuo@gmail.com"
        git config --local user.name "I'm a Code Bot"
        echo  "fuck you" >> hello
        git add --all
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
